### PR TITLE
GA4GH (+ python notebook link + Version schemas in url path backend)

### PR DESCRIPTION
**Pull request by achave11**
Created a link to the python notebook in the github server, from the API link David created in the front end.

### CODE REVIEW

**Comment by maryjgoldman** [comment]
I'm really confused as to why so many of Zack's commits are in this pull request. Aren't they already in our repo?

**Comment by zfisch** [comment]
@achave11 Is this PR intended for Master?

 "merge 88 commits into BD2KGenomics:merge-ga4gh from achave11:merge-ga4gh"

**Comment by achave11** [comment]
No, it was intended for  `http://brcaexchange-dev.cloudapp.net` which I believe is the beta production. Where is currently standing.  I pulled from @david4096  branch and BD2KGenomics:merge-ga4gh where my branch wasn't up to date. So that is why the many commits, I believe. They tagged along from those two forks.

**Comment by zfisch** [comment]
@maryjgoldman this PR is for a separate branch entirely that is not up to date with master (commits are not being recommitted to master, but they are being committed to BD2KGenomics:merge-ga4gh for the first time if this PR is merged). As long as a PR is submitted from BD2KGenomics:merge-ga4gh to master and all merge conflicts are resolved we'll be good.

@achave11 is there somebody with relevant knowledge of your work to review this PR?

**Pull request merged**
